channels:
  - conda-forge
  - bioconda

dependencies:
  - python=2.7
  - pysam>=0.8.1
  - samtools>=1.2
  - bcftools>=1.2
  - bwa>=0.7.12
  - picard>=1.131
  - exonerate>=2.2
  - velvet>=1.2
  - openssl=1.0
